### ISSUE TITLE
Switch to Jakarta Persistence API

### ISSUE THREAD

**Issue by Wooza** [ebean-orm/javax-persistence-api#7]
Hello @rbygrave,

I was wondering if this repository / module is still required.
Or in other words, why not use the "official" API instead? 
```
<dependency>
    <groupId>jakarta.persistence</groupId>
    <artifactId>jakarta.persistence-api</artifactId>
    <version>2.2.3</version>
</dependency>
```

Best regards
Florian

**Comment by rbygrave** [comment]
Q: Can we use the   "official" API?

Yes we can.

Q: Do we want to **only** use the "official" API and get rid of this one?

Not yet given that we have:
https://github.com/ebean-orm/javax-persistence-api/issues?q=is%3Aissue+is%3Aclosed

Some of these issue are open issues in the JPA API and not resolved (e.g. #2).  
Some are things that are nice from an Ebean perspective (#5).  We did that to improve performance of reading the meta model (cost of reading meta annotations plus only look for property mapping annotations on fields and not on getter methods). We could approach this differently as well using annotation processing instead.

I am subscribed to the JPA github repo and watch it and participate but I think it is fair to say I have very little influence and I some concerns that nothing has improved on the JPA mapping side for many years now. It doesn't look to be changing in that regard with very little participation from actual vendors + the state of the eclipselink project suggests it is virtually on ice (apart from the package name change).

So at this stage I expect to maintain this going forward. Note that very likely means the only thing needed to do here is make it a proper java module - have a proper module-info.

**Comment by Wooza** [comment]
Thank you for your lengthy explanation. I was just curious as to why this repo exists, but now it makes sense
