### ISSUE TITLE
Compatibility with Spring Boot 3

### ISSUE THREAD

**Issue by raimy69** [ebean-orm/javax-persistence-api#8]
According to the Spring Boot documentation for SB3 the javax.persistence packages will no longer be supported

https://spring.io/blog/2022/05/24/preparing-for-spring-boot-3-0#:~:text=Check%20if%20Third%2Dparty%20Projects%20Have%20Jakarta%20EE%209%20Compatible%20Releases

Will this package be changed to jakarta.persistence, or will EBean be compatible with Spring Boot 3?

**Comment by rbygrave** [comment]
To be clear Ebean will be compatible with Spring Boot 3 **_WITHOUT_** changing the package here to `jakarta.persistence`.

That is, Spring Boot delegates the ORM aspects to Ebean, it's up to Ebean to do all the ORM functions except ...  

Except for `@Transactional` which can be done by **_either_** Ebean or Spring. That is, we can use Spring managed transactions and their `@Transactional` by using `ebean-spring-txn` - https://github.com/ebean-orm/ebean-spring-txn or use Ebean managed transactions (our `@Transactional` which has a few more features and is the recommended preference).

So in terms of Spring Boot 3 compatibility we are specifically looking at any changes that would break https://github.com/ebean-orm/ebean-spring-txn  

In ebean-spring-txn, we are aware we are using `org.springframework.transaction.support.TransactionSynchronizationAdapter` which is deprecated in favor of the interface `org.springframework.transaction.support.TransactionSynchronization`.  So they could remove the deprecated TransactionSynchronizationAdapter.  We don't want to move to the TransactionSynchronization interface too early so as to support apps on older versions of spring boot but yes we are aware that we might need to make that change for Spring Boot 3. This is a super easy change, we just want to get the timing correct on it and communicate when and why etc.

**However**, there is actually one other detail which will be problematic which is that **JAXB** isn't compatible for both javax and jakarta. Again, that isn't an issue related to this persistence-api but in the area of where Ebean uses JAXB (generating db migrations mostly) and this will be problematic when apps have other libraries using JAXB that don't yet have a version that supports Jakarta JAXB.  

That is, we did look to move Ebean to Jakarta JAXB but found it incompatible for any applications that use other libraries that have a dependency on javax JAXB. So Ebean can bump and support Jakarata JAXB easily enough but this could be a problem area for apps with other libs using javax JAXB that do not have a version that supports Jakarta JAXB. 


Does that make sense?

Cheers, Rob.

**Comment by raimy69** [comment]
Thank you for the detailed explanation, that addresses all the concerns we had. 

I'll close this now.

Thanks,

Ray

**Comment by rbygrave** [comment]
@raimy69 See also https://github.com/ebean-orm/ebean/discussions/2839 and https://github.com/ebean-orm/ebean/issues/2835
